#! /usr/bin/env bash

HOMEgfs=${HOMEgfs:-"/home/Bo.Huang/JEDI-2020/UFS-Aerosols_NRTcyc/UFS-Aerosols_JEDI-AeroDA-1C192-20C192_NRT/"}
ROTDIR=${ROTDIR:-"/scratch2/BMC/gsd-fv3-dev/MAPP_2018/bhuang/JEDI-2020/JEDI-FV3/expRuns/UFS-Aerosols_NRTcyc/"}
PSLOT=${PSLOT:-"UFS-Aerosols_JEDI-AeroDA-1C192-20C192_NRT"}
EXPDIR=${EXPDIR:-"/home/Bo.Huang/JEDI-2020/UFS-Aerosols_NRTcyc/UFS-Aerosols_JEDI-AeroDA-1C192-20C192_NRT/dr-work/"}
TASKRC=${TASKRC:-"/home/Bo.Huang/JEDI-2020/UFS-Aerosols_NRTcyc/UFS-Aerosols_JEDI-AeroDA-1C192-20C192_NRT/dr-work/TaskRecords/cmplCycle_misc.rc"}

CDATE=${CDATE:-"2023072506"}
CYCINTHR=${CYCINTHR:-"06"}

NMEM_ENKF=${NMEM_ENKF:-"20"}
NMEM_EFCSGRP=${NMEM_EFCSGRP:-"2"}

ENSRUN=${ENSRUN:-"YES"}
AERODA=${AERODA:-"YES"}

METDIR_NRT=${METDIR_NRT:-"/scratch1/BMC/gsd-fv3-dev/MAPP_2018/bhuang/JEDI-2020/JEDI-FV3/NRTdata_UFS-Aerosols/GDASAnl/"}
CASE_CNTL=${CASE_CNTL:-"C192"}
CASE_ENKF=${CASE_ENKF:-"C192"}
OBSDIR_NRT=${OBSDIR_NRT:-"/scratch1/BMC/gsd-fv3-dev/MAPP_2018/bhuang/JEDI-2020/JEDI-FV3/NRTdata_UFS-Aerosols/AODObs/"}
CASE_OBS=${CASE_OBS:-"C192"}

ARCHHPSSDIR=${ARCHHPSSDIR:-"/BMC/fim/5year/MAPP_2018/bhuang/UFS-Aerosols-expRuns/UFS-Aerosols_NRTcyc/"}
ARCHRETHR=${ARCHRETHR-"12"}
NMEM_ENSGRP_ARCH=${NMEM_ENSGRP_ARCH:-"10"}

TMPDIR=${ROTDIR}/HERA2HPSS/${CDATE}
[[ ! -d ${TMPDIR} ]] && mkdir -p ${TMPDIR}

cd ${TMPDIR}
cp ${HOMEgfs}/jobs/rocoto/sbatch_arch2hpss_ret.sh ./

cat << EOF > config_hera2hpss
HOMEgfs=${HOMEgfs}
ROTDIR=${ROTDIR}
PSLOT=${PSLOT}

CDATE=${CDATE}
CYCINTHR=${CYCINTHR}

NMEM_ENKF=${NMEM_ENKF}
NMEM_EFCSGRP=${NMEM_EFCSGRP}

ENSRUN=${ENSRUN}
AERODA=${AERODA}

METDIR_NRT=${METDIR_NRT}
CASE_CNTL=${CASE_CNTL}
CASE_ENKF=${CASE_ENKF}

OBSDIR_NRT=${OBSDIR_NRT}
AODTYPE=${AODTYPE}
CASE_OBS=${CASE_OBS}

ARCHHPSSDIR=${ARCHHPSSDIR}
ARCHRETHR=${ARCHRETHR}
NMEM_ENSGRP_ARCH=${NMEM_ENSGRP_ARCH}
HPSSRECORD=${TMPDIR}/../record.failed_HERA2HPSS-${CDATE}

TMPDIR=${TMPDIR}
EOF

/apps/slurm/default/bin/sbatch sbatch_arch2hpss_ret.sh
ERR=$?
echo ${CDATE} > ${TASKRC}
sleep 60

exit ${ERR}
